package cn.martin.mybatis.dao;

import cn.martin.mybatis.model.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insertSelective(Role record);
}