package cn.martin.mybatis.dao;

import cn.martin.mybatis.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insertSelective(UserRole record);
}