package cn.martin.mybatis.dao;

import cn.martin.mybatis.model.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    int insertSelective(User record);

    List<User> getAll();

    List<User> getAll2();

    List<User> getAll3();
}