package cn.martin.mybatis.model;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bid
     *
     * @mbggenerated
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.isbn
     *
     * @mbggenerated
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.encategory
     *
     * @mbggenerated
     */
    private String encategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.cncategory
     *
     * @mbggenerated
     */
    private String cncategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.press
     *
     * @mbggenerated
     */
    private String press;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.pubtime
     *
     * @mbggenerated
     */
    private String pubtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.revision
     *
     * @mbggenerated
     */
    private String revision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.pages
     *
     * @mbggenerated
     */
    private String pages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.cover
     *
     * @mbggenerated
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.disk
     *
     * @mbggenerated
     */
    private String disk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.a
     *
     * @mbggenerated
     */
    private String a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.b
     *
     * @mbggenerated
     */
    private String b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.c
     *
     * @mbggenerated
     */
    private String c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bid
     *
     * @return the value of books.bid
     *
     * @mbggenerated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bid
     *
     * @param bid the value for books.bid
     *
     * @mbggenerated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.name
     *
     * @return the value of books.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.name
     *
     * @param name the value for books.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.path
     *
     * @return the value of books.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.path
     *
     * @param path the value for books.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.isbn
     *
     * @return the value of books.isbn
     *
     * @mbggenerated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.isbn
     *
     * @param isbn the value for books.isbn
     *
     * @mbggenerated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author
     *
     * @return the value of books.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author
     *
     * @param author the value for books.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.encategory
     *
     * @return the value of books.encategory
     *
     * @mbggenerated
     */
    public String getEncategory() {
        return encategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.encategory
     *
     * @param encategory the value for books.encategory
     *
     * @mbggenerated
     */
    public void setEncategory(String encategory) {
        this.encategory = encategory == null ? null : encategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.cncategory
     *
     * @return the value of books.cncategory
     *
     * @mbggenerated
     */
    public String getCncategory() {
        return cncategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.cncategory
     *
     * @param cncategory the value for books.cncategory
     *
     * @mbggenerated
     */
    public void setCncategory(String cncategory) {
        this.cncategory = cncategory == null ? null : cncategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.press
     *
     * @return the value of books.press
     *
     * @mbggenerated
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.press
     *
     * @param press the value for books.press
     *
     * @mbggenerated
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.pubtime
     *
     * @return the value of books.pubtime
     *
     * @mbggenerated
     */
    public String getPubtime() {
        return pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.pubtime
     *
     * @param pubtime the value for books.pubtime
     *
     * @mbggenerated
     */
    public void setPubtime(String pubtime) {
        this.pubtime = pubtime == null ? null : pubtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.revision
     *
     * @return the value of books.revision
     *
     * @mbggenerated
     */
    public String getRevision() {
        return revision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.revision
     *
     * @param revision the value for books.revision
     *
     * @mbggenerated
     */
    public void setRevision(String revision) {
        this.revision = revision == null ? null : revision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.price
     *
     * @return the value of books.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.price
     *
     * @param price the value for books.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.pages
     *
     * @return the value of books.pages
     *
     * @mbggenerated
     */
    public String getPages() {
        return pages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.pages
     *
     * @param pages the value for books.pages
     *
     * @mbggenerated
     */
    public void setPages(String pages) {
        this.pages = pages == null ? null : pages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.cover
     *
     * @return the value of books.cover
     *
     * @mbggenerated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.cover
     *
     * @param cover the value for books.cover
     *
     * @mbggenerated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.disk
     *
     * @return the value of books.disk
     *
     * @mbggenerated
     */
    public String getDisk() {
        return disk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.disk
     *
     * @param disk the value for books.disk
     *
     * @mbggenerated
     */
    public void setDisk(String disk) {
        this.disk = disk == null ? null : disk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.a
     *
     * @return the value of books.a
     *
     * @mbggenerated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.a
     *
     * @param a the value for books.a
     *
     * @mbggenerated
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.b
     *
     * @return the value of books.b
     *
     * @mbggenerated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.b
     *
     * @param b the value for books.b
     *
     * @mbggenerated
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.c
     *
     * @return the value of books.c
     *
     * @mbggenerated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.c
     *
     * @param c the value for books.c
     *
     * @mbggenerated
     */
    public void setC(String c) {
        this.c = c == null ? null : c.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.d
     *
     * @return the value of books.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.d
     *
     * @param d the value for books.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.summary
     *
     * @return the value of books.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.summary
     *
     * @param summary the value for books.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }
}