package cn.martin.mybatis.model;

public class UserRole {

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    private Role role;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.user_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.rold_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    private String roldId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.user_id
     *
     * @return the value of t_user_role.user_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.user_id
     *
     * @param userId the value for t_user_role.user_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.rold_id
     *
     * @return the value of t_user_role.rold_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public String getRoldId() {
        return roldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.rold_id
     *
     * @param roldId the value for t_user_role.rold_id
     *
     * @mbggenerated Wed Jan 21 22:23:41 CST 2015
     */
    public void setRoldId(String roldId) {
        this.roldId = roldId == null ? null : roldId.trim();
    }
}